### ISSUE TITLE
Event-sourced processors for two event logs

### ISSUE THREAD

**Issue by krasserm** [RBMHTechnology/eventuate#100]
See [event-sourced processors](http://rbmhtechnology.github.io/eventuate/architecture.html#event-sourced-processors) section in documentation.

**Comment by Tvaroh** [comment]
When does this feature is planned to be released roughly? Is there some usable code already available in a branch?

**Comment by krasserm** [comment]
@Tvaroh I just [commited](https://github.com/RBMHTechnology/eventuate/commit/0e4a590e58a6e18e4daf260d2a51e7af10b3a307) an [example](https://github.com/RBMHTechnology/eventuate/tree/wip-100-processor-two-logs/src/test/scala/com/rbmhtechnology/example/querydb) using Cassandra as query database. This will be in master next week (and available as 0.5-SNAPSHOT in the our repo). An 0.5 release is planned for beginning of next year.

**Comment by Tvaroh** [comment]
@krasserm awesome, thank you! Does it make sense to just use the `Writer` in your example to update external database, e.g. build some graph, but read it directly using specific API? I mean, `read` that can only return value of one type cannot express all the cases. Or am I misunderstanding the `Writer.read` method purpose?

**Comment by krasserm** [comment]
`Writer.read` is only to initialize the writer (for details, see API docs of [EventsourcedWriter](https://github.com/RBMHTechnology/eventuate/blob/wip-100-processor-two-logs/src/main/scala/com/rbmhtechnology/eventuate/EventsourcedWriter.scala)). Of course, all other queries should use the DB directly.

**Comment by krasserm** [comment]
@Tvaroh Event-sourced writers are now in master (see [documentation](http://rbmhtechnology.github.io/eventuate/reference/event-sourcing.html#event-sourced-writers) for details).

**Comment by Tvaroh** [comment]
@krasserm awesome, will try them out in a near future. Thanks for this awesome work.

Sorry for the unrelated to this discussion question, but what monitoring solution would work better with `eventuate`?

**Comment by krasserm** [comment]
> Thanks for this awesome work.

Thank you for your interest.

> what monitoring solution would work better with eventuate

We are currently evaluating that. Follow #110 for updates.

**Comment by Tvaroh** [comment]
Great, thank you.
