### ISSUE TITLE
Health monitoring

### ISSUE THREAD

**Issue by krasserm** [RBMHTechnology/eventuate#110]

**Comment by Tvaroh** [comment]
Akka-compliant free monitoring solutions I am aware of:

* [Typesage monitoring](https://www.typesafe.com/products/typesafe-monitoring)
* [Kamon](http://kamon.io)
* [Funnel](https://oncue.github.io/funnel/)

Are you planning to support one of these or implement something from scratch?

**Comment by krasserm** [comment]
These tools are on also our radar but we haven't decided yet. Reuse is preferred, with specific additions if needed.

**Comment by krasserm** [comment]
This issue was moved to RBMHTechnology/eventuate-tools#6
