### ISSUE TITLE
Log migration support

### ISSUE THREAD

**Issue by krasserm** [RBMHTechnology/eventuate#111]

**Comment by krasserm** [comment]
Depends on #100

**Comment by hepin1989** [comment]
is this online migrating?and will it be webui based?

**Comment by krasserm** [comment]
@hepin1989 what do you mean by *online migrating*?

**Comment by hepin1989** [comment]
Offline migrating means you need a maintenance window to do the migrate ,like schema rewrite.
online migrate means you don't need to stop the server,and it migrating while your old schema is there,but finally.but finally it will keep in sync ,and you could do the switch.

I have not look very into eventuate,but I think cause it's AP,it maybe come up as a service,which maybe have a web ui for the server side,and on the user side,it's just as it is.

**Comment by krasserm** [comment]
@hepin1989 I think #107 should answers your question(s).

**Comment by hepin1989** [comment]
@krasserm Thank you.

**Comment by krasserm** [comment]
This issue was moved to RBMHTechnology/eventuate-tools#5
