### ISSUE TITLE
Retry initial connection to Cassandra

### ISSUE THREAD

**Issue by krasserm** [RBMHTechnology/eventuate#139]
At the moment, a failing initial connection to a Cassandra cluster (e.g. in cases where the whole cluster is down) causes the `Cassandra` extension initialization to fail.

**Comment by bartlemstra** [comment]
I would like to see this solution in akka-persistence-cassandra as well. Do you have any plans to merge it there?

**Comment by krasserm** [comment]
@bartlemstra yeah, would make sense to have it there as well. Do you want to create a pull request?

**Comment by bartlemstra** [comment]
@krasserm yes, i can do that

**Comment by krasserm** [comment]
@bartlemstra thanks!

**Comment by matlockx** [comment]
That is in fact part of https://github.com/krasserm/akka-persistence-cassandra/issues/121 right?

**Comment by krasserm** [comment]
Not quite, the addition in Eventuate retries an initial connection on in case of a `NoHostAvailableException` whereas the goal of krasserm/akka-persistence-cassandra#121 is to retry schema/table creation.

**Comment by krasserm** [comment]
Anyway, I think both can be combined for krasserm/akka-persistence-cassandra#121.
