### ISSUE TITLE
Dynamic replication networks

### ISSUE THREAD

**Issue by krasserm** [RBMHTechnology/eventuate#142]
It should be possible to add/remove replication connections to/from replication endpoints at runtime.

**Comment by krasserm** [comment]
This ticket also includes the functionality to dynamically turn replication per connection on and off, so that uni-directional replication during application upgrade (#107) can be supported.

**Comment by krasserm** [comment]
Covered by #314. Might become a ticket later but closing for now until decomposition of #314 into work packages becomes more stable.

**Comment by coding4m** [comment]
@krasserm is there any plan to release this feature ?

**Comment by krasserm** [comment]
@coding4m most likely with 0.9, beginning of 2017
