### ISSUE TITLE
Recovery of endpoints terminates too early

### ISSUE THREAD

**Issue by volkerstampa** [RBMHTechnology/eventuate#152]
In case of [disaster recovery](http://rbmhtechnology.github.io/eventuate/reference/event-log.html?highlight=disaster#disaster-recovery) the Future returned by [recover](http://rbmhtechnology.github.io/eventuate/latest/api/index.html#com.rbmhtechnology.eventuate.ReplicationEndpoint@recover%28%29:scala.concurrent.Future[Unit]) completes as soon as all affected endpoints have synchronized their metadata but before the actual event replication took place. If events are written to the event-log that is being recovered, this may result in lost events.

**Comment by krasserm** [comment]
![owl](https://cloud.githubusercontent.com/assets/202907/11451906/d34a4662-95d5-11e5-9be0-5137c2ec00c4.jpg)
