### ISSUE TITLE
Disaster recovery with uni-directional replication

### ISSUE THREAD

**Issue by krasserm** [RBMHTechnology/eventuate#163]
Since implementation of #116, uni-directional (optionally cyclic) replication networks are supported. The current implementation of disaster recovery, however, assumes a bi-directional replication between connected endpoints (see `ReplicationEndpoint.recover()` API docs). For example, given two event logs, A and B at different endpoints, disaster recovery of A requires

- a replication connection from B to A to support metadata re-synchronization at B (*recover metadata* phase)
- a replication connection from A to B to replicate events from B to A (*recover events* phase).

When having a replication connection only from A to B, the current disaster recovery implementation (introduced with #157) would not make progress, as A would never receive a `ReplicationRead` message from B. Disaster recovery at A should therefore skip the *recover metadata* phase if there's only a replication connection from A to B but no replication connection from B to A.

**Comment by krasserm** [comment]
@volkerstampa I don't see this as high priority at the moment as most applications anyway have bi-directional replication links between endpoints.

**Comment by volkerstampa** [comment]
In addition to the fact that A needs to know that the replication link from B to A is _missing_, A also needs to know if there are additional unidirectional replication links from C to A, as in that case C's replication metadata needs to be reset. As A is currently not _aware_ of those it might be an option that in case of recovery an administrator has to list all of A's _incoming_ replication links explicitly.

**Comment by krasserm** [comment]
@volkerstampa is this now resolved with #308?

**Comment by krasserm** [comment]
@volkerstampa I will anyway close this ticket for now as disaster recovery will be re-designed in context of #314. If you think this ticket is still valid, feel free to re-open.
