### ISSUE TITLE
How does eventuate deserialize protobuf messages

### ISSUE THREAD

**Issue by Tvaroh** [RBMHTechnology/eventuate#177]
Hello.

Maybe I'm asking something obvious but how does Eventuate understand what kind of event it is about to process when that event comes in *protobuf*-serialized bytes from, e.g., Cassandra? AFAIK, protobuf doesn't store any information regarding message "type", does it? So, how Eventuate converts those bytes to an event class instance? Is it something managed by Akka?

And related question: is it possible to customize Cassandra storage adapter to include serialized message class name?

**Comment by Tvaroh** [comment]
Found [this](http://doc.akka.io/docs/akka/2.3.9/scala/serialization.html) link in the sources.

```scala
// Turn it back into an object
val back = serializer.fromBinary(bytes, manifest = None)
```

Probably Akka adds some kind of meta-information...

**Comment by krasserm** [comment]
Akka supports manifests and Eventuate actually uses the class manifest [during serialization](https://github.com/RBMHTechnology/eventuate/blob/v-0.4/src/main/scala/com/rbmhtechnology/eventuate/serializer/DurableEventSerializer.scala#L88) and [during deserialization](https://github.com/RBMHTechnology/eventuate/blob/v-0.4/src/main/scala/com/rbmhtechnology/eventuate/serializer/DurableEventSerializer.scala#L131). The manifest is stored in the [PayloadFormat](https://github.com/RBMHTechnology/eventuate/blob/v-0.4/src/main/protobuf/DurableEventFormats.proto#L39) protocol buffers message.

> is it possible to customize Cassandra storage adapter to include serialized message class name?

This is currently not supported as public API. Anyway, you can extract the class name from the serialized message.

**Comment by krasserm** [comment]
Please close this ticket if you think your question is answered. You can also use the [Eventuate Gitter chat room](https://gitter.im/RBMHTechnology/eventuate) for asking questions.

**Comment by Tvaroh** [comment]
Thank you, Martin. It's clear now.

**Comment by krasserm** [comment]
You're welcome!
