### ISSUE TITLE
Error on invalid failure-detection-limit configuration

### ISSUE THREAD

**Issue by kongo2002** [RBMHTechnology/eventuate#184]
Hi,

during some testing I encountered eventuate generating wrong *failure detection* messages when configured via `eventuate.log.replication.failure-detection-limit` with a value less than the actual retry delay of the replication (`eventuate.log.replication.retry-delay`).

Eventuate should rather throw a configuration exception in case the `failure-detection-limit` is not a multiple of the `retry-delay`.

Cheers,
Gregor

**Comment by krasserm** [comment]
Thanks Gregor, 

makes absolutely sense. Will be in the next release. 

Cheers,
Martin
