### ISSUE TITLE
Testing actors (mocking out the eventlog?)

### ISSUE THREAD

**Issue by drozzy** [RBMHTechnology/eventuate#197]
Is there a good way to test event sourced actors?

One would only need to test Cmd -> Evt contracts.
It would be nice to somehow intercept the events before they get sent to the event log (i.e. what write method is doing).

Did anyone have any luck with that?

**Comment by krasserm** [comment]
@drozzy I would prefer that you use the mailing list or the Gitter chatroom for asking questions. If we find out that something is really a missing feature or a bug, open a ticket then. Thank you!

Now to your question: there is currently no special test kit for testing event-sourced actor but you can take a look at [EventsourcedActorSpec](https://github.com/RBMHTechnology/eventuate/blob/master/src/test/scala/com/rbmhtechnology/eventuate/EventsourcedActorSpec.scala) as an example for low-level testing. This however requires knowledge of the [EventsourcingProtocol](https://github.com/RBMHTechnology/eventuate/blob/master/src/main/scala/com/rbmhtechnology/eventuate/EventsourcingProtocol.scala) which should be hidden by a test kit.

I just created #198 for tracking the requirements and development of such a test kit. If you have suggestions for the feature set and the API, please add your comments there. If your question is answered, please close this ticket.
