### ISSUE TITLE
Support SerializerWithStringManifest when serializing event payload and replication filters

### ISSUE THREAD

**Issue by volkerstampa** [RBMHTechnology/eventuate#207]
[Custom Serialization](http://rbmhtechnology.github.io/eventuate/reference/event-sourcing.html#custom-serialization) of events, snapshots and replication filters should support [serializers with string manifest](http://doc.akka.io/docs/akka/2.4.1/scala/serialization.html#Serializer_with_String_Manifest) introduced with akka 2.4.

**Comment by krasserm** [comment]
New [error messages](https://travis-ci.org/RBMHTechnology/eventuate/builds/108493011#L1304) appeared in the build (without failure) since #212 and need investigation.

**Comment by volkerstampa** [comment]
Aren't these error messages expected? As far as I can tell they stem from the tests that try to read bogus snapshots:  `- must fallback to an older snapshot if loading fails` and `- must return None when loading of all snapshots fails`

**Comment by krasserm** [comment]
I just wondered why these error messages didn't appear before. After looking at [this diff](https://github.com/RBMHTechnology/eventuate/commit/893e15011b8a823b2a6808f93716258f6ca01d45#diff-cdce950e8bdad98624fe636753859b47R76) it became clear. Thanks for clarifying.
