### ISSUE TITLE
AbstractEventsourcedProcessorSpec failed

### ISSUE THREAD

**Issue by krasserm** [RBMHTechnology/eventuate#230]
https://travis-ci.org/RBMHTechnology/eventuate/builds/114006751#L975 /cc @cstub. Seems to be a race as it doesn't occur in every test run.

**Comment by krasserm** [comment]
@cstub are the Java tests running concurrently to the Scala tests? This might explain the assertion failure.

**Comment by cstub** [comment]
Unfortunately I was not able to reproduce this behaviour. 

What I did come across was that in the current setup the JUnit-Tests are never executed - this seems to be related to an issue with sbt and the junit test-interface (https://github.com/sbt/junit-interface/issues/35). 
Adding the option 'crossPaths := false' in the testSettings resolves the issue.

The initial test-failure however could not be reproduced, even after enabling the junit tests again.

**Comment by krasserm** [comment]
Will close this ticket for the moment. Let's re-open it should we see the failure again.

**Comment by krasserm** [comment]
Seen again at https://travis-ci.org/RBMHTechnology/eventuate/builds/164556604#L921
