### ISSUE TITLE
Upgrade to Cassandra driver 2.1.9

### ISSUE THREAD

**Issue by krasserm** [RBMHTechnology/eventuate#237]
Applications should be able to use [query latency logging](https://datastax.github.io/java-driver/2.1.9/features/logging/#logging-query-latencies).

**Comment by kongo2002** [comment]
Hi,

although some tests got a bit slower I think this change is worth merging anyways. 

But in order to use the *query logging* facility the `QueryLogger` has to be registered on the `Cluster` instance eventuate is using. Maybe this could be done based on a configuration switch.

Cheers,
Gregor

**Comment by krasserm** [comment]
@kongo2002 +1, will do.

**Comment by krasserm** [comment]
@kongo2002 you have access to a `Cluster` instance via Eventuate's `Cassandra` extension for Akka:

```scala
import com.rbmhtechnology.eventuate.log.cassandra.Cassandra

val system: ActorSystem = ...
val cluster = Cassandra(system).cluster
```

You should have everything you need to register a `QueryLogger`. Do I miss something?

**Comment by kongo2002** [comment]
Yes, you are right - I forgot that I can retrieve the `Cluster` instance like that. Thanks for the hint.

LGTM
