### ISSUE TITLE
EventsourcedView should not extend ActorLogging

### ISSUE THREAD

**Issue by jrieks** [RBMHTechnology/eventuate#259]
`EventsourcedView extends ActorLogging`, which currently makes it hard to create actors extending `DiagnosticActorLogging` - which is required to be able to set MDC values.

Those actors then require an additional `override val log: DiagnosticLoggingAdapter = akka.event.Logging(this)` in order to solve the conflict caused by inheriting both `ActorLogging.log` and `DiagnosticActorLogging.log`.

One simple solution would be to let `EventsourcedView` extend `DiagnosticActorLogging` instead, because the provided `val log: DiagnosticLoggingAdapter` extends the currently used `LoggingAdapter`.

But there are also other `LoggingAdapter` implementations (`BusLogging`, `NoLogging`), so it might make sense to make this somehow configurable?

@krasserm, what do you think?

**Comment by krasserm** [comment]
@jrieks another solution could be that `EventsourcedView` doesn't extend `ActorLogging` or whatever at all but rather define its own `systemLog: LoggingAdapter` for internal use so that it doesn't conflict with `log: LoggingAdapter` from Akka's logging traits. Thoughts?
