### ISSUE TITLE
Stream snapshots to disk with constant memory usage

### ISSUE THREAD

**Issue by jrudolph** [RBMHTechnology/eventuate#265]
`FilesystemSnapshotStore`, currently writes snapshots to disk using akka's `Serialization.serialize` and `Serializer.toBinary` methods. Both methods return a strict byte array which requires that the whole snapshot needs to be buffered in memory before it can be written to disk.

This means that you need to provision a significant amount of additional memory to your Java process to be able to write snapshots all the time (or otherwise, cleverly orchestrate snapshot creation to make sure that enough memory is available at those times). In the worst case of only one EventsourcedActor that contains all the state it would mean that you need to have a heap double the size of your working set to be able to create snapshots.

**Comment by krasserm** [comment]
Covered by #144
