### ISSUE TITLE
Replication connection specific local replication filters

### ISSUE THREAD

**Issue by krasserm** [RBMHTechnology/eventuate#273]
#245 introduced endpoint-global replication filters that apply to all inbound connections. It should be possible to define local replication filters per inbound connection, using a default replication filter if no connection specific filter is defined. It should also be investigated if connection specific local replication filters can make remote replication filters obsolete (which is desired).

**Comment by volkerstampa** [comment]
To maintain backwards compatibility for the moment, support for remote replication filters has not been removed yet. There is a separate issue #297 for this.

**Comment by krasserm** [comment]
I'm re-opening this issue to work on https://github.com/RBMHTechnology/eventuate/pull/294/files#r75814284
