### ISSUE TITLE
Replication/Transport encryption 

### ISSUE THREAD

**Issue by jocsch** [RBMHTechnology/eventuate#28]
As EventSourcedActors are most likely deployed in two different locations and the log gets replicated over the internet it would be very beneficial to have encryption between two endpoints.

**Comment by jacobg** [comment]
I'm exploring eventuate, and see the docs reference transport security as a feature:
http://rbmhtechnology.github.io/eventuate/reference/configuration.html
Does that mean this issue is resolved?

**Comment by volkerstampa** [comment]
@jacobg Thanks for the hint. This issue (and #29) should indeed be resolved via #380.
