### ISSUE TITLE
Authentication for replication

### ISSUE THREAD

**Issue by jocsch** [RBMHTechnology/eventuate#29]
As replication can happen over the internet authentication for replication connections should be supported.

**Comment by krasserm** [comment]
Replication encryption (#28) and authentication (based an akka-remote) seems to be [straightforward](http://doc.akka.io/docs/akka/snapshot/scala/remoting.html#remoting-sample). Gonna schedule it for milestone 0.1.

**Comment by volkerstampa** [comment]
Resolved via #380.
