### ISSUE TITLE
VersionedAggregate and polymorphic classes problem

### ISSUE THREAD

**Issue by owetterau** [RBMHTechnology/eventuate#291]
When using VersionedAggregate (handling an aggregate of type e.g. BaseClass) it seems not to properly create an instance of ClassA which disinherited from BaseClass correctly so that validateUpdate on VersionedAggregate fails with a VersionedAggregate$AggregateDoesNotExistException.

When using the attached Scala class these commands fail:

val polymorphicActor = system.actorOf(PolymorphicActor.props("4711", endpoint.id, eventLog))
polymorphicActor ! CreateClassB("4711", "Test")
polymorphicActor ! SetPropertyTwo("4711", 2)

[PolymorphicActor.scala.txt](https://github.com/RBMHTechnology/eventuate/files/364060/PolymorphicActor.scala.txt)

**Comment by volkerstampa** [comment]
In your `PolymorphicActor#onEvent` when handling `ClassXCreated`-events you do not modify the actor's internal state (`polymorphicAggregate`). It seems when you overwrite your internal state like follows:
```
    case e: ClassACreated =>
        polymorphicAggregate = polymorphicAggregate.handleCreated(e, lastVectorTimestamp, lastSequenceNr)
```
That `SetPropertyTwo` is handled successfully.

**Comment by owetterau** [comment]
Yes, you are right! For whatever reason I have overseen that.
Many thanks for your quick answer!

**Comment by volkerstampa** [comment]
You are welcome.
