### ISSUE TITLE
Optimize ConditionalRequest to require only process id + logical time

### ISSUE THREAD

**Issue by magro** [RBMHTechnology/eventuate#299]
Currently the `ConditionalRequest` requires a full `VectorTime`, which scales with the number of represented processes. From my understanding the conditional request should depend on the logical time of a single process only, so that `ConditionalRequest` could require only a String + Long - independently from the number of involved processes.
If transported via an http etag (or some other header), today the http header would be unnecessarily burdened.  This would be a real issue if the server configured header length gets exceeded, if not it's just inefficient.

Not sure if the optimization is worth it, depends on the use case.

**Comment by krasserm** [comment]
`ConditionalRequest` actually requires the full vector time as it should work across locations (replication endpoints).

**Comment by krasserm** [comment]
Nevermind my previous (meanwhile deleted) comment. +1 on the proposed change.

**Comment by magro** [comment]
Discussed this with Martin:

There might be use cases where a conditional request depends on two events from different logs - so that more than only a single / the local sequence number would be needed.

Even if the application / conditional request depends only on the local sequence number, this is still possible with the current api: a `VectorTime` containing only the local processId + sequence number could be used.

Therefore the proposed change should not be done.
