### ISSUE TITLE
Snapshots: Use lastReceived event in metadata?

### ISSUE THREAD

**Issue by ermanito** [RBMHTechnology/eventuate#309]
Hi @krasserm,

today we paid attention on the snapshot topic. I was wondering why Eventuate considers the lastHandled event for the snapshot write/read process. 

Let's assume the following case:
1. We have actor A and B and two events E1 and E2. 
2. Actor A consumes E1 and actor B consumes E2.
3. Let's say we have just few E1's and millions of E2.
4. When writing a snapshot actor A takes the lastSequenceNo of the latest consumed E1, ignoring the maybe millions of E2 afterwards.
On the next actor recovery, it takes much longer as it needs to.

My question: Wouldn't it be better to take the sequenceNo of the "lastReceived" event instead? Actor A then can start with replication progress with a much higher sequenceNo.

**Comment by krasserm** [comment]
Good catch, thanks for the hint @ermanito. Will schedule the ticket for 0.8. Do you want to make a PR?
