### ISSUE TITLE
SparkStreamAdapterSpecFailed

### ISSUE THREAD

**Issue by krasserm** [RBMHTechnology/eventuate#311]
https://travis-ci.org/RBMHTechnology/eventuate/builds/159545252#L2930

**Comment by volkerstampa** [comment]
A build running the `SparkStreamAdapterSpec` 50 times in a row each time starting sbt just completed [successful](https://travis-ci.org/RBMHTechnology/eventuate/builds/166661792). I am not sure how to reproduce this?!?

**Comment by krasserm** [comment]
I think setting the timeout to 20 seconds (to be consistent with other modules) should be enough for fixing this issue.

**Comment by krasserm** [comment]
Ok, then please close the ticket and re-open if necessary

**Comment by volkerstampa** [comment]
Closed, because not reproducible.
