### ISSUE TITLE
Query directly to the event_store(Event Log) to get history of any event

### ISSUE THREAD

**Issue by knoldernarayan** [RBMHTechnology/eventuate#318]
hi @krasserm we are using eventuate in our project an are stuck in one use case scenarios.
Eventuate is best when we logs the events and they are replayed to the current state , but we are not able to query it directly from the event_store.

Ill explain using a scenario : -

Suppose we have user details with us as Email , 
now when any user updates his email we log an EVENT as EMAIL_UPDATED , with content as new emailID .

again user can update his/her email anytime and each time new EVENT is Logged. now my question is :-

1) How do I fetch the no of times any users has updated the email on a particular Day?

2) How will I get any user updated Email content for any particular data/time ?

3) How to fetch the day/time when any particular user has updated his email from a@gmail.com to b@gmail.com

Now I need to get these details using the EVENT_STORE , means how can i query directly to the event_store ?
Currently we are maintaing the current state through EventSourceView in memory, that is the current updated details for the email , 
but my aim is to get the history for a particular event (like updated Emails).

I have searched a lot on net but didnt get any solution , also on one of the ticket ' https://github.com/RBMHTechnology/eventuate/issues/88 '
 it is mentioned that it not possible using the eventuate to query and fetch directly from event_soure.

So the only solution I am thinking is I need to maintain all the possible state for the particular event in memory which is not fesible in any case.

Please suggest if there is any way to overcome this problem , 
Waiting for any early positive reply , Thanks in advance

**Comment by krasserm** [comment]
@knoldernarayan let's continue the discussion on the Gitter channel, no need to open a duplicate thread here. Please only open a ticket if you think you found an issue with Eventuate. Thanks for your understanding!
