### ISSUE TITLE
One aggregate per actor pattern

### ISSUE THREAD

**Issue by krasserm** [RBMHTechnology/eventuate#36]
Efficiently support the pattern to have one [DDD Aggregate](http://martinfowler.com/bliki/DDD_Aggregate.html) per `EventsourcedActor`. The [example application](https://github.com/RBMHTechnology/eventuate/tree/master/src/test/scala/com/rbmhtechnology/example) still follows the *many aggregates per actor* pattern but it [has already been re-written](https://github.com/wehkamp/eventuate/commit/810112a55cfd0be13a13064f6f822b18c43060d4) by @remcobeckers to follow the *one aggregate per actor* pattern (see also [this discussion](https://github.com/wehkamp/eventuate/commit/810112a55cfd0be13a13064f6f822b18c43060d4#commitcomment-9860644)). Eventuate should support efficient implementations of this pattern by providing the following enhancements:

- the event log must be indexed by aggregate id for efficient recovery of individual aggregates
- if an aggregate actor writes an event, the event log should only notify those aggregate actor replicas with the same aggregate id (and not all other actors subscribed to the event log). Nevertheless, `EventsourcedView`s or non-aggregate `EventsourcedActor`s continue to receive all events written to the event log (to support the *one view for many actors* pattern, for example).
- ~~implement `EventsourcedAggregate` as specialization of `EventsourcedActor` to support implementing the *one aggregate per actor* pattern~~. Update: `EventsourcedActor` has an optional `aggregateId`.
- consider implementing *aggregate services* similar to [CRDT services](https://krasserm.github.io/2015/02/17/Implementing-operation-based-CRDTs/) to free applications from dealing with low-level details.
- the *one aggregate per actor* [prototype](https://github.com/wehkamp/eventuate/commit/810112a55cfd0be13a13064f6f822b18c43060d4) is already implemented in a way that vector clock sizes scale with the number of replicas only instead of the potentially large number of aggregates. Ensure that an implementation of `EventsourcedAggregate` cannot break this property.

**Comment by remcobeckers** [comment]
I didn't have time yet to write this up, so awesome you already took the time! I couldn't have put it more accurate. If all of this is supported it would reduce the amount of code needed for *one aggregate* per actor to the minimum I think.

I was initially thinking of implementing a `VersionedObject` (for a single aggregate) similar to the `VersionedObjects` which I have been heavily borrowing from to implement the *one aggregate* per actor in the example. I think offering an `EventsourcedAggregate` is a better idea. With that the boilerplate needed can be reduced further and the intended usage is much clearer. A `VersionedObject` might be useful in building the `EventsourcedAggregate` though.

**Comment by krasserm** [comment]
@remcobeckers no worries!

Glad that the summary fits your requirements. I agree, something like `VersionedObject` should be part of the implementation as well. Not only for `EventsourcedAggregate` but also for re-use in views. 

I still need to complete some other tickets first but hope to be able to start working on this soon.

**Comment by krasserm** [comment]
@remcobeckers I just committed a first implementation supporting the one-aggregate-per-actor pattern. It introduces an optional `aggregateId` to `EventsourcedActor`. If `aggregateId` is not defined, the actor receives all events from the event log (backwards compatibility). If `aggregateId` is defined, the actor only receives events from `EventsourcedActor` replicas with the same aggregate id (isolating aggregate actors from each other). I did not introduce a separate `EventsourcedAggregate`. This wasn't necessary but could be easily done by applications to require an aggregate id, for example. The Scala example application is re-written and applies the new pattern, the Java example still uses the old n-aggregates-per-actor pattern but I'll rewrite that later too.

The event log is not indexed yet, so an aggregate recovery is a full log scan at the moment but this is an implementation details in the event log. The index will come with one of the next commits (together with user doc and API doc updates and further tests).

Would be great if you could take a look at [the commit](https://github.com/RBMHTechnology/eventuate/commit/40cac57cc3c3ac1ec1b91ae3c0a26443c22d310a) and let me know if it fits your requirements.

Cheers,
Martin
