### ISSUE TITLE
Remove scalaz dependency

### ISSUE THREAD

**Issue by dispalt** [RBMHTechnology/eventuate#366]
I was wondering if you'd be open to ditching your scalaz dependency considering it only has a single use in VectorTime and it's rather heavyweight.

Thoughts?

**Comment by krasserm** [comment]
+1, but we should ensure that performance of `VectorTime` operations doesn't decrease.

**Comment by krasserm** [comment]
@dispalt do you want to make a PR?

**Comment by dispalt** [comment]
Old
