### ISSUE TITLE
Is this thing still on?

### ISSUE THREAD

**Issue by aandr** [RBMHTechnology/eventuate#396]
I'm looking for something exactly like Eventuate for a new project, but I am curious if this project is still in active development. Is it put on hold until Calliope? What are the plans for that, and is it going to be open source? Or is Eventuate not in RBMH's priorities anymore?

Thanks!

**Comment by krasserm** [comment]
@aandr thanks for your interest. Eventuate has several production deployments (at RBMH and other companies) and is actively maintained to support them. I'm one of these maintainers but I'm not doing that full-time any more, just on demand. I also plan to use Eventuate in [akka-stream-eventsourcing](https://github.com/krasserm/akka-stream-eventsourcing) which is experimental work at the moment. I don't know the plans of RBMH regarding Eventuate and Calliope but I'm sure @purthaler can comment on that.

If you're happy with the existing feature set of Eventuate, you can safely use it in production, it is very well tested (including [chaos tests](https://github.com/RBMHTechnology/eventuate-chaos))  and running stable in its current environments.

Hope that helps. For further questions, please use the [Eventuate forum](https://gitter.im/RBMHTechnology/eventuate). 

Cheers,
Martin

**Comment by purthaler** [comment]
Hi @aandr  ,

Thanks a lot for your question. 

On Red Bull Media House side we are currently using Eventuate in various projects in Production. And it works really very well and fully satisfies our demands. Currently we are fine with the set of features Eventuate provides. Therefore Eventuate is currently more in a maintenance mode (bugfixing, upgrade of external dependencies, etc.)

In addition we started to create another project called Calliope. The idea of Calliope can be found in the Wiki post here: [Thoughts on Eventuate’s future](https://github.com/RBMHTechnology/eventuate/wiki/Thoughts-on-Eventuate%E2%80%99s-future) It extracts some key features out of Eventuate. At RBMH we are using Calliope together with Kafka in production.

If you interested in more details how we make use of Eventuate and Calliope within the RBMH, feel free to reach out to me via PN. 

Best regards from Salzburg
Paul
