### ISSUE TITLE
Replication should work with NAT

### ISSUE THREAD

**Issue by krasserm** [RBMHTechnology/eventuate#50]
At the moment, replication is based on [Akka Remoting](http://doc.akka.io/docs/akka/snapshot/scala/remoting.html) which [doesn't support NAT](http://stackoverflow.com/questions/22576020/akka-remote-over-the-internet) (see also [this discussion](https://groups.google.com/forum/#!topic/akka-user/fCD6Nvz9ybg)).

**Comment by krasserm** [comment]
Akka 2.4 will have some [support for NAT](https://github.com/akka/akka/pull/15610). Not sure if we should wait or switch to Finagle anyway for replication. /cc @volkerstampa.

**Comment by volkerstampa** [comment]
The plan seems to be that akka 2.4 is released in [April](https://github.com/akka/akka/pull/15610#issuecomment-72179339), so I think it would be ok to check this out first before switching to Finagle. However there is also this potential problem about [quarantined](http://doc.akka.io/docs/akka/2.3.9/scala/remoting.html#Lifecycle_and_Failure_Recovery_Model) remote systems!?!

**Comment by krasserm** [comment]
> However there is also this potential problem about quarantined remote systems!?!

Good point. This is actually my biggest concern and a good reason to think about (and actually implement) alternatives. Anyway, I'll keep the akka-remote based replication code on a branch so we can try it later with Akka 2.4.

**Comment by krasserm** [comment]
NAT is supported with Akka 2.4 which was tested with a modified configuration on branch [wip-50-nat-support](https://github.com/RBMHTechnology/eventuate/tree/wip-50-nat-support). Also, according to [this post](https://groups.google.com/d/msg/akka-user/NGLi9GTZ42o/7HcBFZgzQwUJ) there's no system message traffic between remote actor systems by default, unless remote deployment or remote death watch is used. Eventuate doesn't use either, so [quarantining](http://doc.akka.io/docs/akka/snapshot/scala/remoting.html#Lifecycle_and_Failure_Recovery_Model) shouldn't be an issue. I therefore propose to use Akka 2.4 as soon as it is released (and not Finagle).

**Comment by volkerstampa** [comment]
Sounds reasonable to me.

**Comment by hepin1989** [comment]
another way maybe implement a p2p(ICE) transport like udt/quic.
but I think just akka 2.4 would be OK.
