### ISSUE TITLE
Plausible clocks

### ISSUE THREAD

**Issue by krasserm** [RBMHTechnology/eventuate#68]
## Overview

At the moment, each instance of `EventsourcedActor` (EA) maintains a vector clock. This allows causality tracking of events that are emitted by different EAs, either at the same location (i.e. to the same [local event log](http://rbmhtechnology.github.io/eventuate/reference/event-log.html#local-event-log)) or at different locations (i.e. to different local event logs that are connected to a [replicated event log](http://rbmhtechnology.github.io/eventuate/reference/event-log.html#replicated-event-log)). In the worst case, this may lead to vector clocks that grow linearly with the number of EAs. This problem could be mitigated by organizing state around aggregates and only routing events between replicas with the same aggregate id, for example.

However, the majority of use cases are about detecting concurrent updates to replicated EA state at **different** locations. EA state is usually not replicated within a single location so that concurrent EA state updates within a location either do not occur or can be detected by other means. This makes causality tracking within a location less important. If we give up causality tracking within a location, all EAs of that location can share an entry in the vector clock. This means that vector clocks only grow with the number of locations (instead of the usually much larger number of EAs). Consequently, tracking of local time (using a counter) can be moved from EAs to the local log actor. A log actor anyway maintains a local counter which is the sequence number of written events. 

EAs at the same location can rely on the fact that they receive all events in the same order. This order is identical with the storage order in the local event log. Should an application still decide to replicate state within a location and concurrent updates are made to these replicas, these updates may be reported as causally related updates which boils down to a *last-writer-wins* conflict resolution strategy.

Assuming a small number of locations, this more coarse-grained approach to causality tracking removes the burden from applications to choose a design and event routing rules that keep vector clock sizes small, yet covering the majority of use cases. We therefore propose to change causality tracking to the described alternative.

## Formalism

The approach described above uses less vector clock entries than sources of concurrent activity (EAs) i.e. EAs at the same location share a vector clock entry. This is formalized in [plausible clocks](http://link.springer.com/article/10.1007%2Fs004460050065). 

With plausible clocks, pairs of causally-related events are correctly ordered by the clock, although some concurrent events may also be ordered. In Eventuate, in particular: 

- events emitted concurrently at the same location may be ordered by the plausible clock, whereas 
- events emitted concurrently at different locations are never ordered by the plausible clock i.e. are always correctly detected as concurrent events.

Given a function **T** that maps events to their vector timestamps, for any two events **x** and **y** emitted at different locations, there is an isomorphism between vector timestamps and the causality relation between these events (see also [`VectorTime`](http://rbmhtechnology.github.io/eventuate/latest/api/index.html#com.rbmhtechnology.eventuate.VectorTime) operators):

- **x** = **y** ⇔ **T(x)** equiv **T(y)** (equivalent)
- **x** → **y** ⇔ **T(x)** < **T(y)** (happened-before)
- **x** ↔︎ **y** ⇔ **T(x)** <> **T(y)** (concurrent)

This is called the *strong clock condition*. For any two events **x** and **y** emitted at the same location, the following condition holds:

- **x** = **y** ⇔ **T(x)** equiv **T(y)** (equivalent) (1)
- **x** → **y** ⇒ **T(x)** < **T(y)** (happened-before) (2)

(1) states that plausible clocks assign unique timestamps and (2) is called the *weak clock condition*. A reported ordering of events **x** and **y** emitted at the same location, means they are either causally related or concurrent whereas a reported concurrency means that they are actually concurrent:

- **T(x)** < **T(y)** ⇒ (**x** → **y**) ∨ (**x** ↔︎ **y**)
- **T(x)** <> **T(y)** ⇒ (**x** ↔︎ **y**)

## Dependent tickets

Plausible clocks are an important prerequisite for [scalable event replication](https://github.com/RBMHTechnology/eventuate/issues/66) and [advanced routing capabilities](https://github.com/RBMHTechnology/eventuate/issues/46).

**Comment by drozzy** [comment]
This sounds great -- are there any problems with this approach?
