### ISSUE TITLE
Batch-oriented persist() result handling

### ISSUE THREAD

**Issue by krasserm** [RBMHTechnology/eventuate#7]
See this [discussion thread](https://groups.google.com/forum/#!topic/eventuate/guBh9eEh3Ew).

**Comment by krasserm** [comment]
@volkerstampa unlike initially discussed, I propose the following solution:

    persistN[A](events: Seq[A], onLast: Try[A] => Unit = _ => ())(handler: Try[A] => Unit): Unit

This is comparable to akka-persistence's ` persist[A](events: Seq[A])(handler: A => Unit)` but allows the caller to specify an `onLast` handler that is additionally invoked after persistence of the *last* event in the sequence.

A batch-oriented persist handler would be in conflict with the `EventsourcedActor`'s `lastSequenceNr` and `lastTimestamp` state which can only be set for _one current_ event. A batch-oriented persist handler doesn't have a single current event but multiple. That's the main reason for this alternative proposal.

Please let me know if it covers your needs.

Cheers,
Martin

**Comment by volkerstampa** [comment]
This looks fine to me. Thanks for implementing it :-)

Volker

**Comment by krasserm** [comment]
Great. Thank you for the use case :)
