### ISSUE TITLE
Generate protobuf Java code during build

### ISSUE THREAD

**Issue by krasserm** [RBMHTechnology/eventuate#72]

**Comment by krasserm** [comment]
See also travis-ci/travis-ci#3341.

**Comment by drozzy** [comment]
Just poking around: great to see protocol buffers! Have you seen proto3 coming out?

**Comment by ddispaltro** [comment]
I'd recommend using something like this http://trueaccord.github.io/ScalaPB/sbt-settings.html with the protoc jar, for basically zero setup protoc compilation.

**Comment by krasserm** [comment]
This looks very interesting, thanks for the pointer.
