### ISSUE TITLE
Handler-specific behavior stacks

### ISSUE THREAD

**Issue by krasserm** [RBMHTechnology/eventuate#90]
[Event-sourcing abstractions](http://rbmhtechnology.github.io/eventuate/architecture.html#event-sourcing) distinguish command processing from event processing using different handlers for it. Hence, event-sourced actors should support both, behavior changes for command-handling and for event handling.

From an implementation perspective, two behavior stacks are needed, one for command handling, the other for event handling. The event-handling behavior stack however will not be stored with snapshots and it is the application's responsibility to restore the appropriate behavior during [snapshot handling](http://rbmhtechnology.github.io/eventuate/reference/event-sourcing.html#snapshots) in `onSnapshot`.

**Comment by Tvaroh** [comment]
Martin, does 'ready' label mean this functionality is available in 0.5 snapshot?

**Comment by krasserm** [comment]
It means [ready for implementation](https://waffle.io/rbmhtechnology/eventuate).
