### ISSUE TITLE
Event deletion

### ISSUE THREAD

**Issue by krasserm** [RBMHTechnology/eventuate#91]
Support deletion of events up to a given sequence number in a local event log. Deletion must
- ~~be coordinated with other locations to avoid invalidation of remote replication progress state~~
- only include events that have already been replicated to other locations. This must be implemented as local decision without requiring coordination with other locations.
- be atomic in order to avoid partial reads

**Comment by krasserm** [comment]
For LevelDB-backed event logs also check that compaction actually works as discussed in akka/akka#13962.

**Comment by volkerstampa** [comment]
I wrote a little test to check the leveldb compaction. It begins with writing n events and then it repeats writing and deleting n events in a loop. So at the end we have n events in the log. After every k iterations the size occupied by the leveldb log is measured.

Just for comparison the first test actually does not delete events at all and writes in total ~ 1 million events.

![nodelete-1mio](https://cloud.githubusercontent.com/assets/2352337/11762509/4fbaa886-a0e9-11e5-9839-748c4d569b85.png)

It took about 2 minitues. As you can see the log consumes roughly  60MB at the end. The next test is basically identical, but does delete events:

![delete-1mio](https://cloud.githubusercontent.com/assets/2352337/11762561/fdf47d68-a0ea-11e5-889f-2500d1d183f0.png)

Here disk-consumption is pretty stable at roughly 3 MB in average. The last test is an extended version that writes in total 20 million events (which took roughly 40 minutes):

![delete-20mio](https://cloud.githubusercontent.com/assets/2352337/11762584/6e231612-a0eb-11e5-8644-29f4f404a562.png)

The disk consumption is slowly raising over time, from ~ 2.9 MB to ~ 4.2 MB
