### ISSUE TITLE
Creation of ReplicationEndpoints with illegal ids should fail

### ISSUE THREAD

**Issue by volkerstampa** [RBMHTechnology/eventuate#99]
The ids of `ReplicationEndpoint`s are used as part of the log-id which in turn is used by the event-log-backends to _name_ their storages. For example the cassandra-backend names the table that is used to store the events after this id. Different backends have different constraints regarding these names and thus regarding the log-id respectively the ReplicationEndpoint-id.

I propose that the creation of an `ReplicationEndpoint` with an _illegal_ id should fail immediately. Another option would be to implement proper escaping of these ids for each event-log-backend.

**Comment by krasserm** [comment]
Covered by #124 (and escaping done by `LeveldbEventLog`).
